### ISSUE TITLE
Threading

### ISSUE THREAD

**Issue by guicho271828** [guicho271828/common-lisp-extensions#11]
https://github.com/sionescu/bordeaux-threads
* special variable binding is rebound at the time make-thread is called. There is also `*default-special-bindings*`.
* lexical variable binding is inherited from the parent thread. When the variable is dynamic-extent, the consequences are undefined.
* make-thread, all-threads, and other mutex/semaphore support.
+ [x] SBCL
+ [x] CCL
+ [x] ECL
+ [ ] CMU
+ [ ] ABCL
+ [x] ALISP

**Comment by ruricolist** [comment]
Bordeaux-Threads also works on ABCL:

https://github.com/sionescu/bordeaux-threads/blob/master/src/impl-abcl.lisp
