### ISSUE TITLE
IEEE float extensions

### ISSUE THREAD

**Issue by guicho271828** [guicho271828/common-lisp-extensions#24]
Support for NaN, Infty, and masking the floating point arithmetic errors. See [ieee-floats](https://github.com/marijnh/ieee-floats) and [float-features](https://github.com/Shinmera/float-features)also. Float-features is more on the complete side.

+ [x] SBCL
+ [x] CCL
+ [x] ECL
+ [x] ABCL
+ [x] ALISP
+ [x] CMU

**Comment by Shinmera** [comment]
Have you read `float-features`' readme? All of these implementations and more are supported.

**Comment by guicho271828** [comment]
That's great. I didnt have enough mental energy to check the detail. I appreciate if you help other tasks too.

**Comment by guicho271828** [comment]
Why are they missing the NaN constants? (I might be misunderstanding NaN)

**Comment by Shinmera** [comment]
Because there is no NaN constant. Multiple IEEE floats can be NaN. That's why there's a `float-nan-p`.

**Comment by guicho271828** [comment]
didn't know that, thanks!

**Comment by guicho271828** [comment]
Given that it covers most impls, it would be safe to say this is a de-facto standard. This issue will be moved to the "defacto standard" status.
