### ISSUE TITLE
macroexpand-all

### ISSUE THREAD

**Issue by guicho271828** [guicho271828/common-lisp-extensions#32]
Feature description:

Supported implementations:
+ [x] [SBCL]()
+ [x] [CCL]()
+ [x] [ECL]()
+ [x] [CMU]()
+ [x] [ABCL]()
+ [x] [ALISP]()

**Comment by y2q-actionman** [comment]
There is [trivial-macroexpand-all](https://github.com/cbaggers/trivial-macroexpand-all) as a compatibility layer.

**Comment by guicho271828** [comment]
moved to the defacto status.
