### ISSUE TITLE
cltl2 environment accessor API

### ISSUE THREAD

**Issue by guicho271828** [guicho271828/common-lisp-extensions#34]
Feature description:
variable-information, function-information
Supported implementations:
+ [x] [SBCL]()
+ [x] [CCL]()
+ [x] [ECL]()
+ [x] [CMU]()
+ [x] [ABCL]()
+ [x] [ALISP]()

**Comment by y2q-actionman** [comment]
There is [trivial-cltl2](https://github.com/Zulu-Inuoe/trivial-cltl2) as a compatibility layer.

**Comment by guicho271828** [comment]
Moved to the de-facto status.
