### ISSUE TITLE
Weak Objects

### ISSUE THREAD

**Issue by g000001** [guicho271828/common-lisp-extensions#40]
Feature description:

Supported implementations:
+ [x] [CLISP]()
+ [x] [SBCL]()
+ [x] [CCL]()
+ [ ] [ECL]()
+ [x] [CMU]()
+ [ ] [ABCL]()
+ [ ] [ACL]()
+ [x] [LispWorks]()

## CLISP

https://clisp.sourceforge.io/impnotes/weak.html#weak-mapping

cf.
https://informatimago.com/develop/lisp/com/informatimago/clext/closer-weak.lisp

**Comment by guicho271828** [comment]
sorry that's already taken --- some issues are closed, plz check the leaderboard
